/// Una fila por reseña y aspecto (Comida, Servicio, Precio, Ambiente). Despivotar permite segmentar por aspecto de forma nativa en Power BI, algo que la tabla ancha original no permite. Mencionado indica si la reseña habló realmente de ese aspecto.
table Aspectos
	lineageTag: a33f5abe-f0e9-4c6a-bb62-d36c25b717d4

	/// Promedio del sentimiento (-1 a 1) contando SOLO las reseñas que mencionaron el aspecto. Si una reseña nunca habla del precio, eso no es evidencia de que el precio sea promedio.
	measure 'Sentimiento promedio' = CALCULATE(AVERAGE(Aspectos[Puntaje]), Aspectos[Mencionado] = TRUE())
		formatString: 0.00
		displayFolder: 2 Sentimiento
		lineageTag: 72856439-d739-42f3-b13a-43b8537600cb

	/// Cuántas reseñas hablaron realmente del aspecto en el contexto actual.
	measure Menciones = CALCULATE(COUNTROWS(Aspectos), Aspectos[Mencionado] = TRUE())
		formatString: #,0
		displayFolder: 2 Sentimiento
		lineageTag: 2ff2ccd8-dc90-4a0a-8cd3-dc00b60f410a

	/// Porcentaje de reseñas que mencionan el aspecto. El precio se comenta mucho menos que la comida.
	measure 'Cobertura de menciones' = DIVIDE([Menciones], COUNTROWS(Aspectos))
		formatString: 0.0%
		displayFolder: 2 Sentimiento
		lineageTag: 9ce18106-3a29-4d26-90f9-2a8660593eed

	measure 'Menciones positivas' = CALCULATE(COUNTROWS(Aspectos), Aspectos[Mencionado] = TRUE(), Aspectos[Sentimiento] = "Positivo")
		formatString: #,0
		displayFolder: 2 Sentimiento
		lineageTag: f109aea6-d220-4e71-870a-7c78c05efe8e

	measure 'Menciones negativas' = CALCULATE(COUNTROWS(Aspectos), Aspectos[Mencionado] = TRUE(), Aspectos[Sentimiento] = "Negativo")
		formatString: #,0
		displayFolder: 2 Sentimiento
		lineageTag: 058f12c6-4183-4742-b609-b6e813843bc4

	/// Proporción de menciones positivas sobre el total de menciones del aspecto.
	measure '% positivas' = DIVIDE([Menciones positivas], [Menciones])
		formatString: 0.0%
		displayFolder: 2 Sentimiento
		lineageTag: 1eaa768c-79ea-4d62-bdaa-f41e6dfcd904

	measure '% negativas' = DIVIDE([Menciones negativas], [Menciones])
		formatString: 0.0%
		displayFolder: 2 Sentimiento
		lineageTag: c57f1628-ffd3-484c-a968-e0c80505584d

	/// Diferencia entre menciones positivas y negativas. Un valor alto indica consenso favorable.
	measure 'Saldo de opinión' = [% positivas] - [% negativas]
		formatString: 0.0%
		displayFolder: 2 Sentimiento
		lineageTag: f2bc0fdd-ef72-4578-9b66-03b9c7999438

	/// Sentimiento del mes previo, para ver si la percepcion mejora o empeora.
	measure 'Sentimiento mes anterior' = CALCULATE([Sentimiento promedio], DATEADD(Calendario[Date], -1, MONTH))
		formatString: 0.00
		displayFolder: 3 Tiempo
		lineageTag: a9087571-ec07-445c-a26a-59c0ccf0b286

	/// Diferencia de sentimiento contra el mes anterior.
	measure 'Cambio de sentimiento' =
			VAR Actual = [Sentimiento promedio]
			VAR Previo = [Sentimiento mes anterior]
			RETURN IF(NOT ISBLANK(Previo), Actual - Previo)
		formatString: +0.00;-0.00;0.00
		displayFolder: 3 Tiempo
		lineageTag: c27b36fe-d4c1-4c50-a42e-6794112a22f1

	/// Sentimiento promedio de todos los restaurantes de la misma cocina, ignorando el resto de filtros de la dimension.
	measure 'Sentimiento de su cocina' = CALCULATE([Sentimiento promedio], ALLEXCEPT(Restaurantes, Restaurantes[CocinaPrincipal]))
		formatString: 0.00
		displayFolder: 4 Comparacion
		lineageTag: 8c02d175-e774-47bf-941f-7919adafb579

	/// Cuánto se despega un restaurante del promedio de su propia cocina. Positivo = mejor que sus pares.
	measure 'Diferencia vs su cocina' = [Sentimiento promedio] - [Sentimiento de su cocina]
		formatString: +0.00;-0.00;0.00
		displayFolder: 4 Comparacion
		lineageTag: 6a3f3902-aca5-4663-89b2-8729d7ee86a8

	measure 'Sentimiento de su zona' = CALCULATE([Sentimiento promedio], ALLEXCEPT(Restaurantes, Restaurantes[Zona]))
		formatString: 0.00
		displayFolder: 4 Comparacion
		lineageTag: d7a02f70-1fbb-4e41-816c-7618a5a19497

	measure 'Diferencia vs su zona' = [Sentimiento promedio] - [Sentimiento de su zona]
		formatString: +0.00;-0.00;0.00
		displayFolder: 4 Comparacion
		lineageTag: 0ec71fc9-4509-47ce-814d-edfe1c94caae

	/// Posición del restaurante según sentimiento, recalculada con lo que el usuario tenga filtrado.
	measure 'Ranking por sentimiento' = IF(NOT ISBLANK([Sentimiento promedio]), RANKX(ALLSELECTED(Restaurantes[Restaurante]), [Sentimiento promedio], , DESC, DENSE))
		formatString: #,0
		displayFolder: 4 Comparacion
		lineageTag: d2c9a938-863f-4b59-b5ed-6a66b18da77d

	/// Distancia entre el aspecto mejor y el peor valorado. Un valor alto señala un restaurante desparejo: por ejemplo, buena comida pero mal servicio.
	measure 'Brecha entre aspectos' =
			VAR Tabla = ADDCOLUMNS(VALUES(Aspectos[Aspecto]), "@S", [Sentimiento promedio])
			VAR Validos = FILTER(Tabla, NOT ISBLANK([@S]))
			VAR Mejor = MAXX(Validos, [@S])
			VAR Peor = MINX(Validos, [@S])
			RETURN IF(COUNTROWS(Validos) > 1, Mejor - Peor)
		formatString: 0.00
		displayFolder: 5 Desbalance
		lineageTag: 9084b832-1e0a-4480-957b-573b3fe9b375

	/// Aspecto con mejor sentimiento en el contexto actual.
	measure 'Mejor aspecto' =
			VAR Tabla = ADDCOLUMNS(VALUES(Aspectos[Aspecto]), "@S", [Sentimiento promedio])
			VAR Validos = FILTER(Tabla, NOT ISBLANK([@S]))
			VAR Maximo = MAXX(Validos, [@S])
			RETURN CONCATENATEX(FILTER(Validos, [@S] = Maximo), Aspectos[Aspecto], ", ")
		displayFolder: 5 Desbalance
		lineageTag: 7d9b35a6-0654-4a96-bce7-749d136af37f

	/// Aspecto con peor sentimiento en el contexto actual.
	measure 'Peor aspecto' =
			VAR Tabla = ADDCOLUMNS(VALUES(Aspectos[Aspecto]), "@S", [Sentimiento promedio])
			VAR Validos = FILTER(Tabla, NOT ISBLANK([@S]))
			VAR Minimo = MINX(Validos, [@S])
			RETURN CONCATENATEX(FILTER(Validos, [@S] = Minimo), Aspectos[Aspecto], ", ")
		displayFolder: 5 Desbalance
		lineageTag: 4ef0c039-249d-4924-8fe2-b99e182e2cb7

	/// Restaurantes que acumulan al menos una mención negativa del aspecto seleccionado.
	measure 'Restaurantes con quejas' = CALCULATE(DISTINCTCOUNT(Aspectos[RestauranteID]), Aspectos[Mencionado] = TRUE(), Aspectos[Sentimiento] = "Negativo")
		formatString: #,0
		displayFolder: 5 Desbalance
		lineageTag: 087b93aa-2f9f-4fd8-964c-63a534d1f4e7

	column ReseñaID
		dataType: int64
		lineageTag: 22e3e5f2-32c0-4139-a4c6-e02244715c3b
		sourceColumn: ReseñaID

	column Aspecto
		dataType: string
		lineageTag: 0223d5cd-e46b-430c-81fd-c402b567737f
		sourceColumn: Aspecto

	column Sentimiento
		dataType: string
		lineageTag: cc5f33c0-5506-4cef-af8a-872360b1a07a
		sourceColumn: Sentimiento

	column Puntaje
		dataType: double
		lineageTag: b8047297-36ff-4799-b301-5a31480e5796
		sourceColumn: Puntaje

	column Mencionado
		dataType: boolean
		lineageTag: 66bab915-a247-43cd-871b-63318c0ee3e9
		sourceColumn: Mencionado

	/// Clave hacia la dimension Restaurantes. Se trae hasta aqui para que Aspectos
	/// apunte directo a sus dimensiones, como exige un modelo en estrella.
	column RestauranteID
		dataType: string
		lineageTag: 9c1f4a20-5b3e-4d71-8e62-1a4f7c93b501
		sourceColumn: RestauranteID

	/// Clave hacia la dimension Calendario.
	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3e8a7b14-6d2c-4f90-a731-5c8e2b46d907
		summarizeBy: none
		sourceColumn: Fecha

		annotation UnderlyingDateTimeDataType = Date

		annotation SummarizationSetBy = Automatic

	partition Aspectos = m
		mode: import
		source =
				let
				    PorAspecto = (nombre as text, colEtiqueta as text, colPuntaje as text, colMencion as text) as table =>
				        let
				            Sel = Table.SelectColumns(DatosProcesados, {"ReseñaID", "restaurant_id", "review_date", colEtiqueta, colPuntaje, colMencion}),
				            Ren = Table.RenameColumns(Sel, {{"restaurant_id", "RestauranteID"}, {"review_date", "Fecha"}, {colEtiqueta, "Sentimiento"}, {colPuntaje, "Puntaje"}, {colMencion, "Mencionado"}}),
				            Con = Table.AddColumn(Ren, "Aspecto", each nombre, type text)
				        in
				            Con,
				    Todos = Table.Combine({
				        PorAspecto("Comida", "sentiment_comida", "sentiment_comida_score", "mentions_comida"),
				        PorAspecto("Servicio", "sentiment_servicio", "sentiment_servicio_score", "mentions_servicio"),
				        PorAspecto("Precio", "sentiment_precio", "sentiment_precio_score", "mentions_precio"),
				        PorAspecto("Ambiente", "sentiment_ambiente", "sentiment_ambiente_score", "mentions_ambiente")
				    }),
				    Etiquetas = Table.TransformColumns(Todos, {{"Sentimiento", each if _ = "positive" then "Positivo" else if _ = "negative" then "Negativo" else "Neutral", type text}}),
				    Logico = Table.TransformColumns(Etiquetas, {{"Mencionado", each _ = "True", type logical}}),
				    Tipos = Table.TransformColumnTypes(Logico, {{"Puntaje", type number}, {"Fecha", type date}}),
				    Orden = Table.SelectColumns(Tipos, {"ReseñaID", "RestauranteID", "Fecha", "Aspecto", "Sentimiento", "Puntaje", "Mencionado"})
				in
				    Orden

